runs:
    using: composite
    steps:
        - uses: ./.github/actions/install-nix
        - shell: bash
          run: nix-shell -p statix --run "statix check"
        - shell: bash
          run: nix-shell -p deadnix --run "deadnix check ."
