name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
    
    - name: Build NixOs WSL tarball
      run: |
        sudo /usr/bin/nix run .#nixosConfigurations.wsl.config.system.build.tarballBuilder
    
    - name: Archive NixOs WSL tarball
      uses: actions/upload-artifact@v4
      with:
        name: nixos-wsl
        path: nixos-wsl.tar.gz