name: "Build NixOs WSL tarball"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix ❄️
      uses: nix-community/NixOS-WSL/.github/actions/install-nix@main
    

    - name: Build Tarball 🛠️
      uses: nix-community/NixOS-WSL/.github/actions/build-wsl-tarball@main
      with:
        config: wsl
        filename: nixos-wsl.tar.gz
         
    - name: Archive NixOs WSL tarball
      uses: actions/upload-artifact@v4
      with:
        name: nixos-wsl
        path: nixos-wsl.tar.gz