name: "Build NixOs WSL tarball"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
    
    - name: Build NixOs WSL expression
      shell: bash
      id: build
      run: |
        JSON=$(mktemp)
        (nix build -L .#nixosConfigurations.wsl.config.system.build.tarballBuilder --no-link --json >$JSON) |& sed -uE 's/^(trace: +)?warning:(\s+|$)/::warning::/;s/^(trace: +)?error:(\s+|$)/::error::/;s/^trace:(\s+|$)/::notice::trace: /'
        DRV=$(jq -r .[0].outputs.out <$JSON)
        echo "derivation=$DRV" >> $GITHUB_OUTPUT
        echo "- Built \`$DRV\`" >> $GITHUB_STEP_SUMMARY
        echo "    - $(nix show-derivation -r $DRV | jq 'keys[]' | wc -l) derivations in closure" >> $GITHUB_STEP_SUMMARY
        echo "    - $(nix path-info -S --json $DRV | jq -r '.[0].closureSize' | xargs numfmt --to=iec-i --suffix=B --format='%.3f') total size" >> $GITHUB_STEP_SUMMARY


    - name: Build NixOs WSL tarball
      id: tarball
      shell: bash
      run: |
       sudo ${{ steps.build.outputs.derivation }}/bin/nixos-wsl-tarball-builder nixos-wsl.tar.gz
    
    - name: Archive NixOs WSL tarball
      uses: actions/upload-artifact@v4
      with:
        name: nixos-wsl
        path: nixos-wsl.tar.gz