name: "Lint Nix config"
run-name: "Lint Nix config"
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/install-nix

    - uses: ./.github/actions/lint